/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appointments;
import appointments.AppointmentsList;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import patients.Patient;
import patients.PatientsList;
/**
 *
 * @author Aaron Diaz
 */
public class FrmAppointment extends javax.swing.JFrame{
    private AppointmentsList appointmentsList;
    private PatientsList patientsList;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAppointment.class.getName());
    /**
     * Creates new form FrmPaciente
     */
    public FrmAppointment() {
        initComponents();
        appointmentsList = new AppointmentsList();
        patientsList = new PatientsList();
    }
    private void clear(){
        txtCodigoCita.setText("");
        txtPaciente.setText("");
        txtCodigoCita.setText("");
        txtHora.setText("");
        txtMotivo.setText("");
        dtcFechaCita.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        lblIdentificacion = new javax.swing.JLabel();
        txtCodigoCita = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        dtcFechaCita = new com.toedter.calendar.JDateChooser();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblMotivo = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        btnVerCitas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnGuardarCita = new javax.swing.JButton();
        btnReprogramar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarporCodigo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pacientes");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Citas");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N

        lblIdentificacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIdentificacion.setText("Código de cita");
        lblIdentificacion.setToolTipText("");

        txtCodigoCita.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Paciente");
        lblNombre.setToolTipText("");

        txtPaciente.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        lblFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFechaNacimiento.setText("Fecha de cita");
        lblFechaNacimiento.setToolTipText("");

        dtcFechaCita.setDateFormatString("dd/MM/yyyy");
        dtcFechaCita.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        lblHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHora.setText("Hora");
        lblHora.setToolTipText("");

        txtHora.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        lblMotivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMotivo.setText("Motivo");
        lblMotivo.setToolTipText("");

        txtMotivo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        btnVerCitas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVerCitas.setText("Ver citas");

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtCodigoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMotivo)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtcFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimiento)
                            .addComponent(btnVerCitas, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(lblNombre)
                    .addComponent(lblFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dtcFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(lblMotivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCitas))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 6));

        btnGuardarCita.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardarCita.setText("Guardar");
        btnGuardarCita.addActionListener(this::btnGuardarCitaActionPerformed);
        jPanel1.add(btnGuardarCita);

        btnReprogramar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnReprogramar.setText("Reprogramar");
        jPanel1.add(btnReprogramar);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar);

        btnBuscarporCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscarporCodigo.setText("Buscar por codigo");
        jPanel1.add(btnBuscarporCodigo);

        btnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        jPanel1.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCitaActionPerformed
    String codigo = txtCodigoCita.getText();
    String idPaciente = txtPaciente.getText();
    String motivo = txtMotivo.getText();
    
        if (codigo.isEmpty() || idPaciente.isEmpty()
            || motivo.isEmpty() || txtHora.getText().isEmpty()|| dtcFechaCita.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
        }
        Patient patient = patientsList.get(idPaciente);
    
        if (patient == null) {
           JOptionPane.showMessageDialog(this, "Paciente no existe"); 
        }
        LocalDate fecha = dtcFechaCita.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        LocalTime hora;
        
        try{
            hora = LocalTime.parse(txtHora.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "La hora debe tener formato HH:mm");
        }
        
        Appointment appointment = new Appointment(
                codigo, patient, fecha, hora, motivo
        );
        
        if (appointmentsList.add(appointment)) {
           JOptionPane.showMessageDialog(this, "Cita guardada correctamente"); 
           
        }else{
            JOptionPane.showMessageDialog(this, "Ya existe una cita con esos datos");
        }
        
    }//GEN-LAST:event_btnGuardarCitaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAppointment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarporCodigo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCita;
    private javax.swing.JButton btnReprogramar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerCitas;
    private com.toedter.calendar.JDateChooser dtcFechaCita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCodigoCita;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
